<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <RootNamespace>WinYouTubeMusic</RootNamespace>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>ytmusic.ico</ApplicationIcon>
    <Title>YouTube Music</Title>
    <Product>YouTube Music</Product>
    <Description>YouTube Music Desktop</Description>
    <Company>KHeresy</Company>
    <AssemblyTitle>YouTube Music</AssemblyTitle>
    <AssemblyProduct>YouTube Music</AssemblyProduct>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="WinUI3\**" />
    <EmbeddedResource Remove="WinUI3\**" />
    <None Remove="WinUI3\**" />
    <Page Remove="WinUI3\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.2903.40" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="ytmusic.ico" />
    <None Update="ytmusic.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <None Update="Scripts\youtube_music_inject.js">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
